checkpoint_dir: '$ROOT_DIR/checkpoints/classification/'
log_dir: '$ROOT_DIR/logs/classification/'
output_save_path: '$ROOT_DIR/results/classification/'
dataset_dir: '$ROOT_DIR/data/mnist/'
model: 'resnet18'
train_epoch: 100
patience: 10
batch_size: 100
learning_rate: 1e-3
weight_decay: 1e-6
num_workers: 8
dataset: 'mnist'
random_seed: 1
linearity_lambda: 1
