checkpoint_dir: '$ROOT_DIR/checkpoints/'
log_dir: '$ROOT_DIR/logs/'
output_save_path: '$ROOT_DIR/results/'
dataset_dir: '$ROOT_DIR/data/mnist/'
train_epoch: 100
patience: 10
batch_size: 100
learning_rate: 1e-3
weight_decay: 1e-6
num_workers: 4
dataset: 'mnist'
random_seed: 1
continuity_lambda: 0.1
