checkpoint_dir: '$ROOT_DIR/checkpoints/'
log_dir: '$ROOT_DIR/logs/'
output_save_path: '$ROOT_DIR/results/'
dataset_dir: '$ROOT_DIR/data/stl10/'
model: 'resnet18'
train_epoch: 200
patience: 20
batch_size: 64
learning_rate: 1e-2
weight_decay: 1e-6
num_workers: 8
dataset: 'stl10'
random_seed: 1
linearity_lambda: 0
